// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egswzrhaitmogerfznpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVnc3d6cmhhaXRtb2dlcmZ6bnBiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NzM3MTUsImV4cCI6MjA2OTQ0OTcxNX0.PFQdpssbzZ-Q7v85CkKxp1mHh2tRAtrVCPMEakbdYTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});